### ISSUE TITLE
Initial Goals for FABRIC

### ISSUE THREAD

**Issue by JWhitleyWork** [upowerrobotics/ros2_fabric#1]
- [x] Enable topic statistics #2
- [x] Calculate the total transmission time on subscriber callback (ROS timestamps) and print it with `RCLCPP_DEBUG` #2
- [x] Find a way to print a `_DEBUG` message at the RMW layer on transmission with the following information: Published topic, timestamp
- [x] Find a way to print a `_DEBUG` message at the RMW layer on reception with the following information: Subscribed topic, timestamp
- [x] Create a Python startup script which can: #4 
  - [x] Read a YAML configuration file for the entire architecture
  - [x] Configure and launch the nodes defined in the configuration file with the correct node name and topic name remappings
  - [x] Accept a parameter for environment name which will cause it to only launch nodes defined in that environment
  - [x] Validates the following rules:
    - [x] Root nodes should have only publishers and no subscribers
    - [x] Terminal nodes should have only subscribers and no publishers
    - [x] It should not be possible to have a node that is both a terminal node and a root node
    - [x] Each publisher needs to have 2 of the following 3 parameters: `bandwidth`, `msg_size`, and/or `msg_frequency`
    - [x] Verify that each publisher has a connected subscriber
    - [x] All `qty` should not be lower than 1
- [x] Create a Python script wich can: #6
  - [x] Gather statistics from log files for a given period or run (maybe using a unique RUN_ID?)
